apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: default
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-world
    image: csdhall/k8s-hello-world:1.0
    env:
      - name: NAME
        value: Christopher
    resources:
      limits:
        cpu: "1"
        memory: "256Mi"
